-- MariaDB
CREATE TABLE `rki_daten` (
	`OBJECTID` INT(11) NOT NULL,
	`GEN` VARCHAR(50) NOT NULL,
	`BEZ` VARCHAR(50) NOT NULL,
	`EWZ` INT(11) NOT NULL,
	`KFL` FLOAT UNSIGNED ZEROFILL NULL DEFAULT NULL,
	`death_rate` FLOAT UNSIGNED ZEROFILL NULL DEFAULT NULL,
	`cases` INT(11) NULL DEFAULT NULL,
	`deaths` INT(11) NULL DEFAULT NULL,
	`cases_per_100k` FLOAT UNSIGNED ZEROFILL NULL DEFAULT NULL,
	`cases_per_population` FLOAT UNSIGNED ZEROFILL NULL DEFAULT NULL,
	`BL` VARCHAR(50) NULL DEFAULT NULL,
	`BL_ID` INT(11) NULL DEFAULT NULL,
	`county` VARCHAR(50) NULL DEFAULT NULL,
	`last_update` VARCHAR(50) NULL DEFAULT NULL,
	`cases7_per_100k` FLOAT UNSIGNED ZEROFILL NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;




